version: "3"
services:
  app:
    container_name: bestcodecomment-node
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - ../:/app:rw,cached
    links:
      - mongo
  mongo:
    container_name: bestcodecomment-mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"